require("presence").setup({
  auto_update         = true,
  neovim_image_text   = "The One True Text Editor",
  main_image          = "neovim",
  client_id           = "793271441293967371",
  log_level           = nil,
  debounce_timeout    = 10,
  enable_line_number  = true,
  blacklist           = {},
  buttons             = true,
  file_assets         = {},
  show_time           = true,
  editing_text        = "Редагую %s",
  file_explorer_text  = "Преглядаю %s",
  git_commit_text     = "Внесення змін",
  plugin_manager_text = "Керування плагінами",
  reading_text        = "Читаю %s",
  workspace_text      = "Працюю на %s",
  line_number_text    = "Рядок %s з %s",
})
